name: "OpenAI Prompt"
description: "Uses OpenAI to generate a prompt response"
author: riccardolinares
branding:
  icon: check-square
  color: black
inputs:
  openai-api-key:
    description: 'Your openai api key'
    required: true
  openai-prompt:
    description: 'The OpenAI prompt'
    require: true
  model:
    description: 'The model to use'
    required: false
    default: 'text-davinci-003'
runs:
  using: 'node16'
  main: 'dist/index.js'
